### PR TITLE
Update submodule, oapi-codegen

### PR DESCRIPTION
**Pull request by Eric-Warehime**
## Summary
In order to update the go-algorand submodule there were a bunch of changes.  
* Updating dependencies in go.mod since go-algorand has bumped these same deps
* Changing block-generator's imports of the algod models
* Updating the oapi-codegen usage for the Indexer APIs. The newer version of the generator caused some type aliases to be created where there previously was none, and changed one of the error messages for 400 responses.

## Test Plan

No new functionality added, so all existing CI/release testing applies.

### CODE REVIEW

**Review by excalq — APPROVED** [review]
Approving, with discussion of WIP lint tests in our slack thread.

**Comment by Eric-Warehime** [comment]
Added a few commits:
* Updated circleCI and the `make lint` command to use golangci-lint
* Various import order changes, spelling fix, etc. that were failing the new lints
* Final fixes for the code gen changes to fix failing tests.

**Comment by winder** [comment]
Looks like this also addresses #1300 :+1:

**Review by winder — APPROVED** [review]

**Review by algobarb — APPROVED** [review]
I mainly am checking that it passes the CircleCI tests and the package build. They LGTM.

**Pull request merged**
