### PR TITLE
Check formatting in CI script.

### PR DESCRIPTION
**Pull request by tolikzinovyev**
## Summary
Run `go fmt` in CI script.

## Test Plan
Any suggestions?

### CODE REVIEW

**Comment by tolikzinovyev** [comment]
I'm a total noob in bash. Suggestions welcome.

**Review by winder — APPROVED** [review]
I'd skip the Makefile and put that right in the travis file. Great idea, I often forget to do this.

**Comment by tolikzinovyev** [comment]
I tried. Travis can't parse the script then. I will see what I can do.

**Comment by winder** [comment]
How about 
```
test -z `go fmt ./...`
```

**Pull request merged**
