### PR TITLE
quick patch to test failures

### PR DESCRIPTION
**Pull request by brianolson**
## Summary

Update to work around test brittleness for new e2e_subs/* data.
Should make this more resilient...

## Test Plan

This is test code, should make automated tests pass.

### CODE REVIEW

**Review by algorandskiy — COMMENTED** [review]
Makes sense for me, please just remove couple commented out var declarations

**Review by winder — APPROVED** [review]
I have the same suggestion as Pavel. Otherwise, LGTM.

**Review by algorandskiy — APPROVED** [review]

**Comment by brianolson** [comment]
I think the most recent build only failed because of docker

**Comment by brianolson** [comment]
do-over in #715  ...

**Comment by brianolson** [comment]
committed #715 version

**Pull request closed without merging**
