### PR TITLE
Delete reverse app deltas

### PR DESCRIPTION
**Pull request by tolikzinovyev**
## Summary

Reverse app deltas are currently written to the database, but are not used. This PR deprecates it and adds a non-blocking migration that deletes the reverse app deltas from the database.

## Test Plan

Migration integration tests.

### CODE REVIEW

**Comment by brianolson** [comment]
Are we sure that we'll _never_ want rewind for apps?

**Comment by tolikzinovyev** [comment]
Maybe. But supporting per-transaction rewinding will require much effort with the new accounting code: go-algorand only gives state changes per block, not per transaction.

**Review by winder — CHANGES_REQUESTED** [review]
Blocked by requirements dependency. @yaovi-a please review.

**Comment by yaovi-a** [comment]
@winder @brianolson If we don't delete the reverse delta data but don't update the logic until a later date, is the data useless?

**Comment by tolikzinovyev** [comment]
@yaovi-a, after talking to @tsachiherman, I'm going to delete the migration and keep the data, just because there is no huge reason to do the migration that might impact Indexer performance.

**Comment by brianolson** [comment]
We are currently generating data that's not used. We could either use it (implement app rewind) OR give up on app rewind and stop generating the reverse-app-deltas and delete them.

**Comment by winder** [comment]
@yaovi-a if we don't update the logic now then the data will become out of date and require a major migration to recompute it later. I think the sort of migration we would require is significantly more expensive with the accounting rewrite than it is with the current custom accounting.

**Comment by yaovi-a** [comment]
@winder, we would have to process every transaction because the rewrite would happen at the block level so excluding app txns wouldn't be possible, correct?

**Comment by winder** [comment]
> @winder, we would have to process every transaction because the rewrite would happen at the block level so excluding app txns wouldn't be possible, correct?

because the rewrite uses algod's accounting which is optimized to work per-block.

**Comment by yaovi-a** [comment]
Ok, unfortunately I don't think we have enough time to update the logic. The data will be useless for now, but we'll just have to revisit rewinding at a later date and decided if we want to update that logic.

**Review by yaovi-a — APPROVED** [review]

**Review by winder — APPROVED** [review]
LGTM

**Pull request merged**
