### PR TITLE
Delete fake migration.

### PR DESCRIPTION
**Pull request by tolikzinovyev**

### CODE REVIEW

**Comment by winder** [comment]
I was kinda proud when I came up with this hack, it's saved us a couple of times when we forgot to update the next migration index (though I suppose it will have to change when we start deprecating them).

**Comment by tolikzinovyev** [comment]
I will make sure each migration has a test that checks the index is incremented. :)

**Comment by winder** [comment]
I think it would be better to replace this with some sort of auto-increment method

**Comment by tolikzinovyev** [comment]
Would you like to contribute?

**Pull request closed without merging**
