### PR TITLE
Add retry loop to block handler.

### PR DESCRIPTION
**Pull request by winder**
## Summary

If the Postgres database handles are exhausted due to many pending queries, block import will fail. With the existing code that would cause Indexer to terminate.

This PR adds a retry loop to ensure the process eventually recover after this sort of transient failure.

## Test Plan

New unit test.

### CODE REVIEW

**Comment by tolikzinovyev** [comment]
How about creating 2 dedicated connections for block import? (`AddBlock()` needs 2).

**Comment by winder** [comment]
> How about creating 2 dedicated connections for block import? (`AddBlock()` needs 2).

I think this is still useful as a basic safety net, but your idea is even better.

Another possible issue is that Aurora replication (presumably) needs its own connection handle(s). One suspicion is this is why our mobile wallet deployments fall behind from time to time. To resolve that one we might need to make the pgx pool size configurable. Seems like [ConnectConfig](https://pkg.go.dev/github.com/jackc/pgx/v4/pgxpool#ConnectConfig) has plenty of options for doing that.

**Comment by tolikzinovyev** [comment]
I'm just not sure ignoring an error is a good solution.

Not following about aurora replication.

**Comment by winder** [comment]
> I'm just not sure ignoring an error is a good solution.
It doesn't ignore the error. An error is logged, it's up to the service runner to decide whether or not to ignore errors.

> Not following about aurora replication.
I can follow up on this separately.

**Comment by winder** [comment]
@tolikzinovyev I created some followup tickets to reduce the chance that this will happen:
#826 
#827

**Review by AlgoStephenAkiki — APPROVED** [review]

**Review by shiqizng — APPROVED** [review]
looks fine.

**Review by tolikzinovyev — APPROVED** [review]
Looks good!

**Pull request merged**
