### PR TITLE
Preload asset/app creators before evaluation

### PR DESCRIPTION
**Pull request by tolikzinovyev**
## Summary

Preloading asset/app creators in a batch improves performance by ~10%.

Depends on #746.

### CODE REVIEW

**Review by winder — COMMENTED** [review]
This looks correct, but should it be part of the EvalForIndexer interface? I thought that interface's main purpose was to make it easier to preload everything.

**Comment by tolikzinovyev** [comment]
> This looks correct, but should it be part of the EvalForIndexer interface? I thought that interface's main purpose was to make it easier to preload everything.

I don't think I understand.

**Comment by winder** [comment]
> > This looks correct, but should it be part of the EvalForIndexer interface? I thought that interface's main purpose was to make it easier to preload everything.
> 
> I don't think I understand.

I'm asking about the design here, not the implementation.

You're using a combination of these new methods:
```
	LookupWithoutRewards(map[basics.Address]struct{}) (map[basics.Address]*basics.AccountData, error)
	GetAssetCreator(map[basics.AssetIndex]struct{}) (map[basics.AssetIndex]FoundAddress, error)
	GetAppCreator(map[basics.AppIndex]struct{}) (map[basics.AppIndex]FoundAddress, error)
```

I thought one reason for those methods was to avoid needing this sort of preloading, so I wonder if the interface is wrong.

Should it be a single method instead of 3? Or perhaps we add a 4th method to the interface specifically designed to help with caching.

**Comment by tolikzinovyev** [comment]
If your suggestion is to have the code that decides what to preload in go-algorand, then @tsachiherman was against it. We still need the interface functions in case we forget to preload something and the evaluator needs it. Let me know if this doesn't quite answer your questions.

**Comment by tsachiherman** [comment]
@winder - there are two "faces" for the evaluator:
We try to preload all the required resources before the evaluation. However, if during evaluation we find that we need additional resources, we need to provide the functionality to retrieve them.

The reason the evaluator need to be "dynamic" is that it's also being used for the transaction pool, where we add transactions on the fly. I wouldn't oppose to open a discussion on whether the evaluator need to be resource-predictable or not ( outside the scope of this PR ).

**Comment by winder** [comment]
@tolikzinovyev @tsachiherman thanks for the explanations. I guess the difference between algod and indexer is that algod's caching system exists outside of these functions and Indexer's is using them to initialize the cache.

It might be good to rename this function to something like `preloadEvalResources` to be more specific about what sort of preparation is happening.

Do we need to modify `GetAssetCreator` and `GetAppCreator` to check the cache? Wouldn't the evaluator call these functions a second time after preloading everything?

**Pull request merged**
