### PR TITLE
Improve DB indexes for better worst case accounting time

### PR DESCRIPTION
**Pull request by tolikzinovyev**
## Summary

Closes https://github.com/algorand/go-algorand-internal/issues/1718.

## Test Plan

Ran block generator. No noticeable difference in performance.

### CODE REVIEW

**Review by gmalouf — CHANGES_REQUESTED** [review]
Question: Do we need to manage migration for existing deployments, or are we just assuming no backwards compatibility with upcoming release / simply deleting references to pre-existing indexes? cc @winder 

I.E. Some of these indexes being updated it seems we would want runners to drop before applying the new ones, yet we give no on/off ramp to do this at first glance.

**Comment by tolikzinovyev** [comment]
The coming "refactoring" release will no backward compatibility with the previous ones. The users will have to create a new database and do catch up from round 0. This is simply because 2.6.* has accounting problems, and 2.7 will in all likelihood crash if we try using a 2.6 database. Hence, we should use the opportunity to make any changes that would require a migration if we were to support backward compatibility.

**Comment by gmalouf** [comment]
I'm approving, but have we run tests with these indexes at least locally to show the performance improvement?

**Review by gmalouf — APPROVED** [review]

**Review by gmalouf — COMMENTED** [review]
We need to keep in mind that not everyone uses the same indexes, although these in particular -should- be universal. We'll need to work with release eng to communicate the changes in existing ones for people who pick and choose which ones they apply today..

**Review by winder — APPROVED** [review]
Seems fine to me.

**Comment by tolikzinovyev** [comment]
> I'm approving, but have we run tests with these indexes at least locally to show the performance improvement?

The performance is asymptotically better in the worst case (when the number of deleted items is much larger than the number of non-deleted items). I'm not sure testing performance is even necessary.

**Pull request merged**
