### PR TITLE
Format schema sql

### PR DESCRIPTION
**Pull request by tolikzinovyev**
## Summary

Makes formatting consistent.

### CODE REVIEW

**Review by winder — CHANGES_REQUESTED** [review]
Something weird is going on, why are there mixed tabs and spaces?

**Comment by tolikzinovyev** [comment]
Where? I see only spaces in .sql and only tabs in .go.

**Comment by winder** [comment]
I should have been more specific, the mixed indentation is outside of the diff:

image

**Comment by tolikzinovyev** [comment]
I think I didn't run `go generate` after my last edit. It's fixed now.

**Review by winder — APPROVED** [review]

**Pull request merged**
