### PR TITLE
Use our own json handle for decoding

### PR DESCRIPTION
**Pull request by tolikzinovyev**
## Summary

We already use our own json handle for encoding. For consistency and to guard against changes in go-algorand, use the same json handle for decoding.

### CODE REVIEW

**Review by gmalouf — COMMENTED** [review]
Why move the jsonCodeHandle into a new `encoding.go` file in the same package? Readability, or is there something obvious I am missing?

**Review by winder — CHANGES_REQUESTED** [review]
I agree with the comments Brian made some time ago. I'd rather see encoding/decoding merged into a single file with all functions side-by-side. For me, separate encode/decode files make this code more difficult to read and review, further separation would make things even more difficult.

https://github.com/algorand/indexer/pull/611#discussion_r686858713

**Comment by tolikzinovyev** [comment]
> I agree with the comments Brian made some time ago. I'd rather see encoding/decoding merged into a single file with all functions side-by-side. For me, separate encode/decode files make this code more difficult to read and review, further separation would make things even more difficult.
> 
> [#611 (comment)](https://github.com/algorand/indexer/pull/611#discussion_r686858713)

I really think it's not a problem, as you can have two windows side-by-side, but I put encoding, decoding functions in the same file.

**Review by winder — APPROVED** [review]
LGTM

**Review by gmalouf — APPROVED** [review]

**Pull request merged**
