### PR TITLE
Pass IndexerDbOptions by value

### PR DESCRIPTION
**Pull request by tolikzinovyev**
## Summary
I think there is no reason to have a pointer.

## Test Plan
The change is trivial.

### CODE REVIEW

**Review by brianolson — CHANGES_REQUESTED** [review]
Why do you like by-value better? Isn't `nil` a better signal of 'nothing set'?
By value copies the whole contents of the struct every time, pointer doesn't.

**Comment by tolikzinovyev** [comment]
Mainly for the sake of readability. Then you don't need wonder if `nil` is somehow different from `&IndexerOptions{}`. Also the user of `opts` doesn't need to check for `nil` every time a field needs to be read. It's true that pointer might be more efficient, but it's just initialization code, so doesn't matter.

**Review by winder — APPROVED** [review]
The change seems fine to me. I guess this would be a more functional approach, it's nice that it avoids some weird nil checks during initialization.

**Comment by tolikzinovyev** [comment]
@winder I rebased it, please approve

**Review by winder — APPROVED** [review]

**Pull request merged**
